### ISSUE TITLE
No repeats option for trainer to quickly go through all selected OLLs

### ISSUE THREAD

**Issue by bugybunny** [Roman-/oll_trainer#1]
Someone on reddit said he wanted to do this https://www.reddit.com/r/Cubers/comments/85uycn/none_of_the_oll_trainers_i_could_find_have_a_no/. I’ve never thought about this but I agree that it would be a handy feature, not just for OLL training.

**Comment by Roman-** [comment]
Great idea!
One little problem is that if I select a small group of OLLs, the last case will be predictable. I'll think about introducing this feature soon.

**Comment by Roman-** [comment]
Done. See this post: https://www.speedsolving.com/forum/threads/released-oll-trainer.66924/#post-1282493

**Comment by Arsid433** [comment]
Hey! Arsid here, thanks for doing this so fast! Now the flashcards I made are worthless lol.

> One little problem is that if I select a small group of OLLs, the last case will be predictable. I'll think about introducing this feature soon.

I don't really see that as a problem if you're just trying to do a quick review of all the ones you know so far. As long as you can do a scramble that's different than a solution and then solve it with your usual alg, I don't think it'll change anything if you know which ones are left.
