### ISSUE TITLE
Nothing happens when I click "ready"

### ISSUE THREAD

**Issue by fwdekker** [Roman-/oll_trainer#4]
After selecting some cases to train, and then clicking "Train", I see the scramble to perform and the text "ready" in the middle. But when I click on or near "ready", nothing happens. From the GIF in the README I understood that clicking there would start the timer, but that doesn't happen on my machine.

I tried with the latest Firefox and Chromium, but neither worked for me. The browser's console does not show any errors either.

**Comment by Roman-** [comment]
You are supposed to use the spacebar to start the timer. For mobile devices, touching is also supported.

**Comment by fwdekker** [comment]
Oh I see! Thanks for the help :-)
